// The human labels of ESI location flags, the legacy Static/LocationFlag
// map (mirrored by the Rust location_flag_label); unknown flags fall
// back to the raw value.

const LABELS: Record<string, string> = {
	AssetSafety: 'Asset Safety',
	AutoFit: 'Auto Fit',
	BoosterBay: 'Booster Bay',
	Cargo: 'Cargo',
	CorporationGoalDeliveries: 'Corporation Goal Deliveries',
	CorpseBay: 'Corpse Bay',
	Deliveries: 'Deliveries',
	DroneBay: 'Drone Bay',
	FighterBay: 'Fighter Bay',
	FighterTube0: 'Fighter Tube 0',
	FighterTube1: 'Fighter Tube 1',
	FighterTube2: 'Fighter Tube 2',
	FighterTube3: 'Fighter Tube 3',
	FighterTube4: 'Fighter Tube 4',
	FleetHangar: 'Fleet Hangar',
	FrigateEscapeBay: 'Frigate Escape Bay',
	Hangar: 'Hangar',
	HangarAll: 'Hangar All',
	HiSlot0: 'High Slot 1',
	HiSlot1: 'High Slot 2',
	HiSlot2: 'High Slot 3',
	HiSlot3: 'High Slot 4',
	HiSlot4: 'High Slot 5',
	HiSlot5: 'High Slot 6',
	HiSlot6: 'High Slot 7',
	HiSlot7: 'High Slot 8',
	HiddenModifiers: 'Hidden Modifiers',
	Implant: 'Implant',
	LoSlot0: 'Low Slot 1',
	LoSlot1: 'Low Slot 2',
	LoSlot2: 'Low Slot 3',
	LoSlot3: 'Low Slot 4',
	LoSlot4: 'Low Slot 5',
	LoSlot5: 'Low Slot 6',
	LoSlot6: 'Low Slot 7',
	LoSlot7: 'Low Slot 8',
	Locked: 'Locked',
	MedSlot0: 'Med Slot 1',
	MedSlot1: 'Med Slot 2',
	MedSlot2: 'Med Slot 3',
	MedSlot3: 'Med Slot 4',
	MedSlot4: 'Med Slot 5',
	MedSlot5: 'Med Slot 6',
	MedSlot6: 'Med Slot 7',
	MedSlot7: 'Med Slot 8',
	MobileDepotHold: 'Mobile Depot Hold',
	QuafeBay: 'Quafe Bay',
	RigSlot0: 'Rig Slot 0',
	RigSlot1: 'Rig Slot 1',
	RigSlot2: 'Rig Slot 2',
	RigSlot3: 'Rig Slot 3',
	RigSlot4: 'Rig Slot 4',
	RigSlot5: 'Rig Slot 5',
	RigSlot6: 'Rig Slot 6',
	RigSlot7: 'Rig Slot 7',
	ShipHangar: 'Ship Hangar',
	Skill: 'Skill',
	SpecializedAmmoHold: 'Specialized Ammo Hold',
	SpecializedAsteroidHold: 'Specialized Asteroid Hold',
	SpecializedCommandCenterHold: 'Specialized Command Center Hold',
	SpecializedFuelBay: 'Specialized Fuel Bay',
	SpecializedGasHold: 'Specialized Gas Hold',
	SpecializedIceHold: 'Specialized Ice Hold',
	SpecializedIndustrialShipHold: 'Specialized Industrial Ship Hold',
	SpecializedLargeShipHold: 'Specialized Large Ship Hold',
	SpecializedMaterialBay: 'Specialized Material Bay',
	SpecializedMediumShipHold: 'Specialized Medium Ship Hold',
	SpecializedMineralHold: 'Specialized Mineral Hold',
	SpecializedOreHold: 'Specialized Ore Hold',
	SpecializedPlanetaryCommoditiesHold: 'Specialized Planetary Commodities Hold',
	SpecializedSalvageHold: 'Specialized Salvage Hold',
	SpecializedShipHold: 'Specialized Ship Hold',
	SpecializedSmallShipHold: 'Specialized Small Ship Hold',
	StructureDeedBay: 'Structure Deed Bay',
	SubSystemBay: 'Sub System Bay',
	SubSystemSlot0: 'Sub System Slot 0',
	SubSystemSlot1: 'Sub System Slot 1',
	SubSystemSlot2: 'Sub System Slot 2',
	SubSystemSlot3: 'Sub System Slot 3',
	SubSystemSlot4: 'Sub System Slot 4',
	SubSystemSlot5: 'Sub System Slot 5',
	SubSystemSlot6: 'Sub System Slot 6',
	SubSystemSlot7: 'Sub System Slot 7',
	Unlocked: 'Unlocked',
	Wardrobe: 'Wardrobe',
	CorpSAG1: 'Corp Hangar 1',
	CorpSAG2: 'Corp Hangar 2',
	CorpSAG3: 'Corp Hangar 3',
	CorpSAG4: 'Corp Hangar 4',
	CorpSAG5: 'Corp Hangar 5',
	CorpSAG6: 'Corp Hangar 6',
	CorpSAG7: 'Corp Hangar 7',
	InfrastructureHangar: 'Infrastructure Hangar',
	CorpDeliveries: 'Corp Deliveries',
	CapsuleerDeliveries: 'Capsuleer Deliveries',
	ExpeditionHold: 'Expedition Hold'
};

export function locationFlagLabel(flag: string): string {
	return LABELS[flag] ?? flag;
}
